#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

currentDir=`pwd`

read -r -p "Please confirm? [Y/n] " input
 
case $input in
    [yY][eE][sS]|[yY])
       echo "Updating all test_*.dat output files in solution"
       for output_path in `find . -maxdepth 1 \( -type f -a -name 'test_*.dat' \)`
       do
           echo $output_path
           cp $output_path ./solution/
       done
       ;;
    [nN][oO]|[nN])
       echo "Aborted"
       ;;
    *)
 echo "Invalid input"
 exit 1
 ;;
esac
